name: Production CI Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build_website:
    runs-on: ubuntu-22.04

    name: Build and deploy website
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Build website
      shell: bash
      run: |
        make BUILDDIR="build/en" html
        mv build/en/html/ output/

    - name: Build German translation
      run: |
        make BUILDDIR="build/de" SPHINXOPTS="-Dlanguage=de" html
        mv build/de/html/ output/de/

    - name: Build Japanese translation
      run: |
       make BUILDDIR="build/ja" SPHINXOPTS="-Dlanguage=ja" html
       mv build/ja/html/ output/ja/

    - name: Build traditional Chinese translation
      run: |
       make BUILDDIR="build/zh_Hant" SPHINXOPTS="-Dlanguage=zh_Hant" html
       mv build/zh_Hant/html/ output/zh_Hant/


    - name: Deploy website
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.tuxfamily.org
        username: ${{ secrets.GHA_FTP_USER }}
        password: ${{ secrets.GHA_FTP_PASS }}
        local-dir: ./output/
        server-dir: overte/overte.org-web/htdocs/
        exclude: |
          .htaccess
