name: Master CI Check Warnings

on:
  push:
    branches:
      - master

jobs:
  check_warnings:
    runs-on: ubuntu-20.04

    name: Check for warnings
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check source documentation
      shell: bash
      run: |
        make SPHINXOPTS="-W --keep-going" html
    - name: Check German documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-de SPHINXOPTS="-Dlanguage=de -W --keep-going" html
    - name: Check French documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-fr SPHINXOPTS="-Dlanguage=fr -W --keep-going" html
    - name: Check Japanese documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-jp SPHINXOPTS="-Dlanguage=jp -W --keep-going" html
    - name: Check Spanish documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-es SPHINXOPTS="-Dlanguage=es -W --keep-going" html
    - name: Check Korean documentation
      if: ${{ success() || failure() }}
      shell: bash
      run: |
        make BUILDDIR=build-ko SPHINXOPTS="-Dlanguage=ko -W --keep-going" html
