name: Master CI Check Links

on:
  push:
    branches:
      - master
    # Only run if something other than locales are updated.
    # This is to prevent this workflow from running when Weblate commits new translations, since we only check the source language.
    paths-ignore:
      - 'source/locales/**'
jobs:
  check_links:
    runs-on: ubuntu-20.04

    name: Check for broken links
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check links in documentation
      shell: bash
      run: |
        make SPHINXOPTS="-W --keep-going" linkcheck
